<?php

return [
	'state_list' => array(
		'' => '',
		'1' => 'Andaman and Nicobar Islands',
		'2' => 'Andhra Pradesh',
		'3' => 'Arunachal Pradesh',
		'4' => 'Assam',
		'5' => 'Bihar',
		'6' => 'Chandigarh',
		'7' => 'Chhattisgarh',
		'8' => 'Dadra and Nagar Haveli',
		'9' => 'Daman and Diu',
		'10' => 'Delhi',
		'11' => 'Goa',
		'12' => 'Gujarat',
		'13' => 'Haryana',
		'14' => 'Himachal Pradesh',
		'15' => 'Jammu and Kashmir',
		'16' => 'Jharkhand',
		'17' => 'Karnataka',
		'18' => 'Kerala',
		'19' => 'Lakshadweep',
		'20' => 'Madhya Pradesh',
		'21' => 'Maharashtra',
		'22' => 'Manipur',
		'23' => 'Meghalaya',
		'24' => 'Mizoram',
		'25' => 'Nagaland',
		'26' => 'Odisha',
		'27' => 'Pondicherry',
		'28' => 'Punjab',
		'29' => 'Rajasthan',
		'30' => 'Sikkim',
		'31' => 'Tamil Nadu',
		'32' => 'Telangana',
		'33' => 'Tripura',
		'34' => 'Uttaranchal',
		'35' => 'Uttar Pradesh',
		'36' => 'West Bengal'
	),
	'verification_path' => 'http://172.16.8.115/project/training/public/'
];
